name: pytest

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Miniconda
        run: |
          wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
          bash miniconda.sh -b -p $HOME/miniconda
          echo "$HOME/miniconda/bin" >> $GITHUB_PATH
          source "$HOME/miniconda/etc/profile.d/conda.sh"
          conda init bash
          conda config --set always_yes yes --set changeps1 no
          conda --version
        shell: bash

      - name: Install Kwant via conda
        run: |
          source "$HOME/miniconda/etc/profile.d/conda.sh"
          conda info
          conda env create -f env_kwant.yml --verbose
          echo "Initialized Conda and created MyKwant env"
          conda activate MyKwant
          echo "Activated MyKwant conda env"
          conda list
          python -c "import kwant; print(f'Kwant version: {kwant.__version__}')"
        shell: bash

      - name: Install other dependencies
        run: |
          source "$HOME/miniconda/etc/profile.d/conda.sh"
          conda activate MyKwant
          python -m pip install --upgrade pip
          python -m pip install "numpy<2" scipy matplotlib tqdm sympy pytest
          echo "Installed pip, tqdm, matplotlib, scipy, numpy, sympy, pytest"
          python setup.py install
          echo "Installed xkwant by setup.py"
        shell: bash

      - name: Run Pytest
        run: |
          source "$HOME/miniconda/etc/profile.d/conda.sh"
          conda activate MyKwant
          pytest test.py
        shell: bash
